---
- name: Purge old packages
  ansible.builtin.apt:
    name: '{{ item }}'
    state: absent
    update_cache: true
  register: apt_status
  until: apt_status is success
  delay: 6
  retries: 10
  with_items:
    - docker
    - docker.io
    - containerd
    - runc
  when: ansible_os_family == 'Debian'
...
